### ISSUE TITLE
Illegal state for JWSObject during token generation

### ISSUE THREAD

**Issue by hzbarcea** [apifocal/activemq-mix#14]
The token generation code leads to the following `Exception`, using for instance one of the test private keys:

```
$ amix-token -u user -a app -i bob -k jaas/amix-auth-token/src/test/resources/ssh/id_rsa-bob
Exception in thread "main" java.lang.IllegalStateException: The JWS object must be in a signed or verified state
	at com.nimbusds.jose.JWSObject.ensureSignedOrVerifiedState(JWSObject.java:273)
	at com.nimbusds.jose.JWSObject.serialize(JWSObject.java:394)
	at org.apifocal.amix.tools.token.TokenApp.createToken(TokenApp.java:144)
	at org.apifocal.amix.tools.token.TokenApp.main(TokenApp.java:105)
```

**Comment by hzbarcea** [comment]
The #18 PR fixed this issue. Not sure why this was not closed automatically, looks like I did not use the github conventions the right way. Closing issue.
